"""change_email_to_barcode

Revision ID: 37a02e8cd663
Revises: 97247d11a7a6
Create Date: 2022-06-15 19:39:46.325830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37a02e8cd663'
down_revision = '97247d11a7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('barcode', sa.Integer(), nullable=False))
    op.drop_index('email', table_name='users')
    op.create_unique_constraint(None, 'users', ['barcode'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('email', 'users', ['email'], unique=False)
    op.drop_column('users', 'barcode')
    # ### end Alembic commands ###
