"""add telegram

Revision ID: 515879135627
Revises: 37a02e8cd663
Create Date: 2022-06-16 00:55:49.513776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515879135627'
down_revision = '37a02e8cd663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram')
    # ### end Alembic commands ###
