"""add rating

Revision ID: f06269435b1c
Revises: cff98767e2a3
Create Date: 2022-05-25 04:35:52.143220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06269435b1c'
down_revision = 'cff98767e2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating')
    # ### end Alembic commands ###
